### ISSUE TITLE
update "@junobuild/core": "^0.0.35",

### ISSUE THREAD

**Issue by 7flash** [peterpeterparker/icdraw#2]
but unfortunately then shows an error in devtools:

```
decoder.js:58 Uncaught (in promise) ReferenceError: global is not defined
    at new _Decoder (decoder.js:58:26)
    at new Uint8ArrayDecoder (cbor.ts:105:1)
    at decode2 (cbor.ts:121:19)
    at _HttpAgent.query (index.ts:438:47)
    at async caller (actor.ts:394:22)
    at async L (doc.api.ts:24:50)
    at async rt (user.services.ts:16:34)
    at async q (auth.services.ts:21:16)
    at async ds (index.ts:24:3)
    at async App.tsx:14:7
_Decoder @ decoder.js:58
Uint8ArrayDecoder @ cbor.ts:105
decode2 @ cbor.ts:121
query @ index.ts:438
await in query (async)
(anonymous) @ App.tsx:19
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 14 more frames
Show less
```

**Comment by peterpeterparker** [comment]
Fck me! I think I know what it is, it's because of changes in the packaging library of yesterday to solve an issue with Next.js. Let me try to fix that...

Thanks for the report.

**Comment by peterpeterparker** [comment]
@7flash can you try the very last version of the libraries which I have just published?

This should solve the issue. Please let me know if it works out. Thanks in advance for your help.

**Comment by peterpeterparker** [comment]
I just bumped to v0.0.36 and redeployed https://icdraw.com/. All seems good.

Thanks a lot for the ping!!!
